const express = require("express");
const dotenv = require("dotenv");
const mongoose = require("mongoose");
const moment = require("moment");
const morgan = require("morgan");
var methodOverride = require("method-override");
var database = require("./config/database");
const GroupCompany = require("./models/Groupcompany.js")



dotenv.config();
const app = express();

mongoose.connect(
  database.cosmosdbUrl,
  {
    useNewUrlParser: true,
    useCreateIndex: true,
    useUnifiedTopology: true,
    useFindAndModify: false,
  },
  async () => {
    console.log("db connected");
await GroupCompany.create([
   
    {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "CCRP",
        persaText: "Group Corporate Office",
        employeeGroup: ["1", "2", "4", "5"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "CCRP",
        persaText: "Group Corporate Office",
        employeeGroup: ["1", "2", "5"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "CCRP",
        persaText: "Group Corporate Office",
        employeeGroup: ["1", "2"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "SCNT",
        persaText: "Systech Centre",
        employeeGroup: ["1", "2", "4", "5"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "SCNT",
        persaText: "Systech Centre",
        employeeGroup: ["1", "2", "5"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "SCNT",
        persaText: "Systech Centre",
        employeeGroup: ["1", "2"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "PCNT",
        persaText: "Mahindra & Mahindra Ltd",
        employeeGroup: ["1", "2", "4", "5"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "PCNT",
        persaText: "Mahindra & Mahindra Ltd",
        employeeGroup: ["1", "2", "5"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "PCNT",
        persaText: "Mahindra & Mahindra Ltd",
        employeeGroup: ["1", "2"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "ADSS",
        persaText: "Aero Defense and Steel Sector",
        employeeGroup: ["1", "2", "4", "5"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "ADSS",
        persaText: "Aero Defense and Steel Sector",
        employeeGroup: ["1", "2", "5"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "ADSS",
        persaText: "Aero Defense and Steel Sector",
        employeeGroup: ["1", "2"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "MSSL",
        persaText: "Mobility Services Sector",
        employeeGroup: ["1", "2", "4", "5"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "MSSL",
        persaText: "Mobility Services Sector",
        employeeGroup: ["1", "2", "5"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "MSSL",
        persaText: "Mobility Services Sector",
        employeeGroup: ["1", "2"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "AAUT",
        persaText: "Auto-Automotive Division",
        employeeGroup: ["1", "2", "4", "5"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "AAUT",
        persaText: "Auto-Automotive Division",
        employeeGroup: ["1", "2", "5"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "AAUT",
        persaText: "Auto-Automotive Division",
        employeeGroup: ["1", "2"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "ADCE",
        persaText: "Construction Equipment",
        employeeGroup: ["1", "2", "4", "5"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "ADCE",
        persaText: "Construction Equipment",
        employeeGroup: ["1", "2", "5"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "ADCE",
        persaText: "Construction Equipment",
        employeeGroup: ["1", "2"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "AFIO",
        persaText: "AFS - INTL. OPS.",
        employeeGroup: ["1", "2", "4", "5"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "AFIO",
        persaText: "AFS - INTL. OPS.",
        employeeGroup: ["1", "2", "5"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "AFIO",
        persaText: "AFS - INTL. OPS.",
        employeeGroup: ["1", "2"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "AMRV",
        persaText: "Auto-MRV",
        employeeGroup: ["1", "2", "4", "5"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "AMRV",
        persaText: "Auto-MRV",
        employeeGroup: ["1", "2", "5"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "AMRV",
        persaText: "Auto-MRV",
        employeeGroup: ["1", "2"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
    
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "ASFD",
        persaText: "AFS",
        employeeGroup: ["1", "2", "4", "5"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "ASFD",
        persaText: "AFS",
        employeeGroup: ["1", "2", "5"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "ASFD",
        persaText: "AFS",
        employeeGroup: ["1", "2"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "ASSG",
        persaText: "AFS-Sourcing",
        employeeGroup: ["1", "2", "4", "5"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "ASSG",
        persaText: "AFS-Sourcing",
        employeeGroup: ["1", "2", "5"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "ASSG",
        persaText: "AFS-Sourcing",
        employeeGroup: ["1", "2"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
    
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "CMRV",
        persaText: "Corporate MRV",
        employeeGroup: ["1", "2", "4", "5"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "CMRV",
        persaText: "Corporate MRV",
        employeeGroup: ["1", "2", "5"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "CMRV",
        persaText: "Corporate MRV",
        employeeGroup: ["1", "2"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "EXVN",
        persaText: "External Vendor",
        employeeGroup: ["1", "2", "4", "5"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "EXVN",
        persaText: "External Vendor",
        employeeGroup: ["1", "2", "5"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "EXVN",
        persaText: "External Vendor",
        employeeGroup: ["1", "2"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "FAGB",
        persaText: "FES-Agri Business",
        employeeGroup: ["1", "2", "4", "5"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "FAGB",
        persaText: "FES-Agri Business",
        employeeGroup: ["1", "2", "5"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "FAGB",
        persaText: "FES-Agri Business",
        employeeGroup: ["1", "2"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
    
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "FDGD",
        persaText: "FES-POWEROL",
        employeeGroup: ["1", "2", "4", "5"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "FDGD",
        persaText: "FES-POWEROL",
        employeeGroup: ["1", "2", "5"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "FDGD",
        persaText: "FES-POWEROL",
        employeeGroup: ["1", "2"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "FMHD",
        persaText: "FES-Mahindra Division",
        employeeGroup: ["1", "2", "4", "5"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "FMHD",
        persaText: "FES-Mahindra Division",
        employeeGroup: ["1", "2", "5"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "FMHD",
        persaText: "FES-Mahindra Division",
        employeeGroup: ["1", "2"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "FMRV",
        persaText: "FES-MRV",
        employeeGroup: ["1", "2", "4", "5"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "FMRV",
        persaText: "FES-MRV",
        employeeGroup: ["1", "2", "5"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "FMRV",
        persaText: "FES-MRV",
        employeeGroup: ["1", "2"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "FSWD",
        persaText: "FES-Swaraj Division",
        employeeGroup: ["1", "2", "4", "5"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "FSWD",
        persaText: "FES-Swaraj Division",
        employeeGroup: ["1", "2", "5"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "FSWD",
        persaText: "FES-Swaraj Division",
        employeeGroup: ["1", "2"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "MMSB",
        persaText: "After Markets ( MSB)",
        employeeGroup: ["1", "2", "4", "5"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "MMSB",
        persaText: "After Markets ( MSB)",
        employeeGroup: ["1", "2", "5"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "MMSB",
        persaText: "After Markets ( MSB)",
        employeeGroup: ["1", "2"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
    
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "MTBD",
        persaText: "Truck and Bus Division",
        employeeGroup: ["1", "2", "4", "5"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "MTBD",
        persaText: "Truck and Bus Division",
        employeeGroup: ["1", "2", "5"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "MTBD",
        persaText: "Truck and Bus Division",
        employeeGroup: ["1", "2"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
    
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "SMRV",
        persaText: "Systech-MRV",
        employeeGroup: ["1", "2", "4", "5"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "SMRV",
        persaText: "Systech-MRV",
        employeeGroup: ["1", "2", "5"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "SMRV",
        persaText: "Systech-MRV",
        employeeGroup: ["1", "2"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "TCNT",
        persaText: "Two Wheeler Corporate Centre",
        employeeGroup: ["1", "2", "4", "5"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "TCNT",
        persaText: "Two Wheeler Corporate Centre",
        employeeGroup: ["1", "2", "5"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "TCNT",
        persaText: "Two Wheeler Corporate Centre",
        employeeGroup: ["1", "2"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "TPDS",
        persaText: "TRK PTD ADV TEC & MRV CMN SRVS",
        employeeGroup: ["1", "2", "4", "5"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "TPDS",
        persaText: "TRK PTD ADV TEC & MRV CMN SRVS",
        employeeGroup: ["1", "2", "5"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "TPDS",
        persaText: "TRK PTD ADV TEC & MRV CMN SRVS",
        employeeGroup: ["1", "2"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "TTWS",
        persaText: "TWS-Mahindra 2W Sector",
        employeeGroup: ["1", "2", "4", "5"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "TTWS",
        persaText: "TWS-Mahindra 2W Sector",
        employeeGroup: ["1", "2", "5"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1001",
        companyName: "Mahindra & Mahindra Ltd",
        persaCode: "TTWS",
        persaText: "TWS-Mahindra 2W Sector",
        employeeGroup: ["1", "2"],
        employeeGrade: ["AV","AU","AF","GP","PU","AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS","2Q","SU","ST","2O","2S","2R","SS","TA","TB","2T","3T","TJ","GU","C6","C7"],
      },
      {
        companyCode: "1039",
        companyName: "Tech Mahindra Ltd.",
        persaCode: "TCML",
        persaText: "Tech Mahindra Ltd.",
        employeeGroup: ["1", "2", "4", "5"],
        employeeGrade: ["AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS"],
      },
      {
        companyCode: "1039",
        companyName: "Tech Mahindra Ltd.",
        persaCode: "TCML",
        persaText: "Tech Mahindra Ltd.",
        employeeGroup: ["1", "2", "5"],
        employeeGrade: ["AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS"],
      },
      {
        companyCode: "1039",
        companyName: "Tech Mahindra Ltd.",
        persaCode: "TCML",
        persaText: "Tech Mahindra Ltd.",
        employeeGroup: ["1", "2"],
        employeeGrade: ["AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS"],
      },
      {
        companyCode: "1020",
        companyName: "Mahindra Heavy Engine Ltd",
        persaCode: "AMNE",
        persaText: "Auto-MHEL",
        employeeGroup: ["1", "2", "4", "5"],
        employeeGrade: []
      },
      {
        companyCode: "1020",
        companyName: "Mahindra Heavy Engine Ltd",
        persaCode: "AMNE",
        persaText: "Auto-MHEL",
        employeeGroup: ["1", "2", "5"],
        employeeGrade: [""],
      },
      {
        companyCode: "1020",
        companyName: "Mahindra Heavy Engine Ltd",
        persaCode: "AMNE",
        persaText: "Auto-MHEL",
        employeeGroup: ["1", "2"],
        employeeGrade: [""],
      },
    
      {
        companyCode: "1021",
        companyName: "Mahindra Vehicle Mfg. Ltd",
        persaCode: "AMVM",
        persaText: "Auto-MVML",
        employeeGroup: ["1", "2", "4", "5"],
        employeeGrade: [""],
      },
      {
        companyCode: "1021",
        companyName: "Mahindra Vehicle Mfg. Ltd",
        persaCode: "AMVM",
        persaText: "Auto-MVML",
        employeeGroup: ["1", "2", "5"],
        employeeGrade: [""],
      },
      {
        companyCode: "1021",
        companyName: "Mahindra Vehicle Mfg. Ltd",
        persaCode: "AMVM",
        persaText: "Auto-MVML",
        employeeGroup: ["1", "2"],
        employeeGrade: [""],
      },
      {
        companyCode: "1024",
        companyName: "Mahindra Two Wheelers Ltd",
        persaCode: "TMTW",
        persaText: "TWS-Mahindra 2W (MTWL)",
        employeeGroup: ["1", "2", "4", "5"],
        employeeGrade: ["AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS"],
      },
      {
        companyCode: "1024",
        companyName: "Mahindra Two Wheelers Ltd",
        persaCode: "TMTW",
        persaText: "TWS-Mahindra 2W (MTWL)",
        employeeGroup: ["1", "2", "5"],
        employeeGrade: ["AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS"],
      },
      {
        companyCode: "1024",
        companyName: "Mahindra Two Wheelers Ltd",
        persaCode: "TMTW",
        persaText: "TWS-Mahindra 2W (MTWL)",
        employeeGroup: ["1", "2"],
        employeeGrade: ["AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS"],
      },
    
      {
        companyCode: "1036",
        companyName: "GROMAX AGRI EQUIPMENT LIM",
        persaCode: "GAEL",
        persaText: "Gromax Agri Equipment Ltd",
        employeeGroup: ["1", "2", "4", "5"],
        employeeGrade: ["KN","KO","KM","KQ","KU","KR","KP","KS","KT","KL","KZ","KH"],
      },
      {
        companyCode: "1036",
        companyName: "GROMAX AGRI EQUIPMENT LIM",
        persaCode: "GAEL",
        persaText: "Gromax Agri Equipment Ltd",
        employeeGroup: ["1", "2", "5"],
        employeeGrade: ["KN","KO","KM","KQ","KU","KR","KP","KS","KT","KL","KZ","KH"],
      },
      {
        companyCode: "1036",
        companyName: "GROMAX AGRI EQUIPMENT LIM",
        persaCode: "GAEL",
        persaText: "Gromax Agri Equipment Ltd",
        employeeGroup: ["1", "2"],
        employeeGrade: ["KN","KO","KM","KQ","KU","KR","KP","KS","KT","KL","KZ","KH"],
      },
      {
        companyCode: "1037",
        companyName: "Mahindra Elect Mob. Ltd",
        persaCode: "ARVA",
        persaText: "Mahindra Reva Electric Vehicle",
        employeeGroup: ["1", "2", "4", "5"],
        employeeGrade: ["AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS"],
      },
      {
        companyCode: "1037",
        companyName: "Mahindra Elect Mob. Ltd",
        persaCode: "ARVA",
        persaText: "Mahindra Reva Electric Vehicle",
        employeeGroup: ["1", "2", "5"],
        employeeGrade: ["AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS"],
      },
      {
        companyCode: "1037",
        companyName: "Mahindra Elect Mob. Ltd",
        persaCode: "ARVA",
        persaText: "Mahindra Reva Electric Vehicle",
        employeeGroup: ["1", "2"],
        employeeGrade: ["AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS"],
      },
    
      
      {
        companyCode: "1049",
        companyName: "Mahindra Agri Solutions",
        persaCode: "FSSL",
        persaText: "Mahindra Agri Solutions",
        employeeGroup: ["1", "2", "4", "5"],
        employeeGrade: ["HU","HR","PU","HT","A9","HN","HL","HM","HP","HO","HQ","HK","HV","A2","C6","A1","A0"],
      },
      {
        companyCode: "1049",
        companyName: "Mahindra Agri Solutions",
        persaCode: "FSSL",
        persaText: "Mahindra Agri Solutions",
        employeeGroup: ["1", "2", "5"],
        employeeGrade: ["HU","HR","PU","HT","A9","HN","HL","HM","HP","HO","HQ","HK","HV","A2","C6","A1","A0"],
      },
      {
        companyCode: "1049",
        companyName: "Mahindra Agri Solutions",
        persaCode: "FSSL",
        persaText: "Mahindra Agri Solutions",
        employeeGroup: ["1", "2"],
        employeeGrade: ["HU","HR","PU","HT","A9","HN","HL","HM","HP","HO","HQ","HK","HV","A2","C6","A1","A0"],
      },
      {
        companyCode: "1054",
        companyName: "Mahindra HZPC Pvt. Ltd.",
        persaCode: "FIPL",
        persaText: "Mahindra HZPC",
        employeeGroup: ["1", "2", "4", "5"],
        employeeGrade: ["HU","HP","HO","HR","HN","HM","HL","HQ","HK","A0","C6"],
      },
      {
        companyCode: "1054",
        companyName: "Mahindra HZPC Pvt. Ltd.",
        persaCode: "FIPL",
        persaText: "Mahindra HZPC",
        employeeGroup: ["1", "2", "5"],
        employeeGrade: ["HU","HP","HO","HR","HN","HM","HL","HQ","HK","A0","C6"],
      },
      {
        companyCode: "1054",
        companyName: "Mahindra HZPC Pvt. Ltd.",
        persaCode: "FIPL",
        persaText: "Mahindra HZPC",
        employeeGroup: ["1", "2"],
        employeeGrade: ["HU","HP","HO","HR","HN","HM","HL","HQ","HK","A0","C6"],
      },
      {
        companyCode: "1055",
        companyName: "Mahindra Greenyard Pvt Ltd",
        persaCode: "FUPL",
        persaText: "Mahindra Univeg Pvt Ltd",
        employeeGroup: ["1", "2", "4", "5"],
        employeeGrade: [""],
      },
      {
        companyCode: "1055",
        companyName: "Mahindra Greenyard Pvt Ltd",
        persaCode: "FUPL",
        persaText: "Mahindra Univeg Pvt Ltd",
        employeeGroup: ["1", "2", "5"],
        employeeGrade: [""],
      },
      {
        companyCode: "1055",
        companyName: "Mahindra Greenyard Pvt Ltd",
        persaCode: "FUPL",
        persaText: "Mahindra Univeg Pvt Ltd",
        employeeGroup: ["1", "2"],
        employeeGrade: [""],
      },
    
      {
        companyCode: "1063",
        companyName: "MAHINDRA EPC IRRIGATION Limited",
        persaCode: "MEPC",
        persaText: "Mahindra EPC Industrie Ltd.",
        employeeGroup: ["1", "2", "4", "5"],
        employeeGrade: [""],
      },
      {
        companyCode: "1063",
        companyName: "MAHINDRA EPC IRRIGATION Limited",
        persaCode: "MEPC",
        persaText: "Mahindra EPC Industrie Ltd.",
        employeeGroup: ["1", "2", "5"],
        employeeGrade: [""],
      },
      {
        companyCode: "1063",
        companyName: "MAHINDRA EPC IRRIGATION Limited",
        persaCode: "MEPC",
        persaText: "Mahindra EPC Industrie Ltd.",
        employeeGroup: ["1", "2"],
        employeeGrade: [""],
      },
      {
        companyCode: "1065",
        companyName: "TRRINGO.COM LIMITED",
        persaCode: "FTRN",
        persaText: "TRRINGO.COM LIMITED",
        employeeGroup: ["1", "2", "4", "5"],
        employeeGrade: [""],
      },
      {
        companyCode: "1065",
        companyName: "TRRINGO.COM LIMITED",
        persaCode: "FTRN",
        persaText: "TRRINGO.COM LIMITED",
        employeeGroup: ["1", "2", "5"],
        employeeGrade: [""],
      },
      {
        companyCode: "1065",
        companyName: "TRRINGO.COM LIMITED",
        persaCode: "FTRN",
        persaText: "TRRINGO.COM LIMITED",
        employeeGroup: ["1", "2"],
        employeeGrade: [""],
      },
    
      {
        companyCode: "1068",
        companyName: "Mahindra Waste to Energy Solutions Ltd",
        persaCode: "MWTE",
        persaText: "Mahindra Waste to Energy Solutions",
        employeeGroup: ["1", "2", "4", "5"],
        employeeGrade: [""],
      },
      {
        companyCode: "1068",
        companyName: "Mahindra Waste to Energy Solutions Ltd",
        persaCode: "MWTE",
        persaText: "Mahindra Waste to Energy Solutions",
        employeeGroup: ["1", "2", "5"],
        employeeGrade: [""],
      },
      {
        companyCode: "1068",
        companyName: "Mahindra Waste to Energy Solutions Ltd",
        persaCode: "MWTE",
        persaText: "Mahindra Waste to Energy Solutions",
        employeeGroup: ["1", "2"],
        employeeGrade: [""],
      },
      {
        companyCode: "1070",
        companyName: "MAHINDRA SUMMIT AGRISCIENCE LTD",
        persaCode: "FMSA",
        persaText: "Mahindra Summit Agriscience",
        employeeGroup: ["1", "2", "4", "5"],
        employeeGrade: ["HP","HT","HN","HM","HL","HO","HQ","HK","HV","HR","HU"],
      },
      {
        companyCode: "1070",
        companyName: "MAHINDRA SUMMIT AGRISCIENCE LTD",
        persaCode: "FMSA",
        persaText: "Mahindra Summit Agriscience",
        employeeGroup: ["1", "2", "5"],
        employeeGrade: ["HP","HT","HN","HM","HL","HO","HQ","HK","HV","HR","HU"],
      },
      {
        companyCode: "1070",
        companyName: "MAHINDRA SUMMIT AGRISCIENCE LTD",
        persaCode: "FMSA",
        persaText: "Mahindra Summit Agriscience",
        employeeGroup: ["1", "2"],
        employeeGrade: ["HP","HT","HN","HM","HL","HO","HQ","HK","HV","HR","HU"],
      },
      {
        companyCode: "1071",
        companyName: "Mahindra eMarket Limited",
        persaCode: "MEML",
        persaText: "Mahindra eMarket Limited",
        employeeGroup: ["1", "2", "4", "5"],
        employeeGrade: ["GI","GK","GJ","GL","KP"],
      },
      {
        companyCode: "1071",
        companyName: "Mahindra eMarket Limited",
        persaCode: "MEML",
        persaText: "Mahindra eMarket Limited",
        employeeGroup: ["1", "2", "5"],
        employeeGrade: ["GI","GK","GJ","GL","KP"],
      },
      {
        companyCode: "1071",
        companyName: "Mahindra eMarket Limited",
        persaCode: "MEML",
        persaText: "Mahindra eMarket Limited",
        employeeGroup: ["1", "2"],
        employeeGrade: ["GI","GK","GJ","GL","KP"],
      },
      {
        companyCode: "9005",
        companyName: "Mahindra Contech Ltd.",
        persaCode: "CCON",
        persaText: "M&M Contech",
        employeeGroup: ["1", "2", "4", "5"],
        employeeGrade: ["AP","AI" ,"A2" ,"A0" ,"A1" ,"A3" , "JI" , "JJ", "6J","6K" ,"6L" ,"JK" ,"A7"],
      },
      {
        companyCode: "9005",
        companyName: "Mahindra Contech Ltd.",
        persaCode: "CCON",
        persaText: "M&M Contech",
        employeeGroup: ["1", "2", "5"],
        employeeGrade: ["AP","AI" ,"A2" ,"A0" ,"A1" ,"A3" , "JI" , "JJ", "6J","6K" ,"6L" ,"JK" ,"A7"],
      },
      {
        companyCode: "9005",
        companyName: "Mahindra Contech Ltd.",
        persaCode: "CCON",
        persaText: "M&M Contech",
        employeeGroup: ["1", "2"],
        employeeGrade: ["AP","AI" ,"A2" ,"A0" ,"A1" ,"A3" , "JI" , "JJ", "6J","6K" ,"6L" ,"JK" ,"A7"],
      },
      {
        companyCode: "9025",
        companyName: "Classic Legends Private Ltd",
        persaCode: "CLPL",
        persaText: "Classic Legends Pvt. Ltd.",
        employeeGroup: ["1", "2", "4", "5"],
        employeeGrade: [""],
      },
      {
        companyCode: "9025",
        companyName: "Classic Legends Private Ltd",
        persaCode: "CLPL",
        persaText: "Classic Legends Pvt. Ltd.",
        employeeGroup: ["1", "2", "5"],
        employeeGrade: [""],
      },
      {
        companyCode: "9025",
        companyName: "Classic Legends Private Ltd",
        persaCode: "CLPL",
        persaText: "Classic Legends Pvt. Ltd.",
        employeeGroup: ["1", "2"],
        employeeGrade: [""],
      },
      {
        companyCode: "9026",
        companyName: "Swaraj Engines Limited.",
        persaCode: "FSEL",
        persaText: "Swaraj Engines Limited.",
        employeeGroup: ["1", "2", "4", "5"],
        employeeGrade: ["AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS"],
      },
      {
        companyCode: "9026",
        companyName: "Swaraj Engines Limited.",
        persaCode: "FSEL",
        persaText: "Swaraj Engines Limited.",
        employeeGroup: ["1", "2", "5"],
        employeeGrade: ["AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS"],
      },
      {
        companyCode: "9026",
        companyName: "Swaraj Engines Limited.",
        persaCode: "FSEL",
        persaText: "Swaraj Engines Limited.",
        employeeGroup: ["1", "2"],
        employeeGrade: ["AD","AC","AB","AA","A9","A8","A7","A6","A5","A4","A3","A2","A1","A0","TI","TK","TG","MS"],
      },
  
    
    
],
  
      function (err, employee) {
        if (err) console.log(err);

     
        console.log("created");
      }
    );
  }
);

app.use(morgan("dev"));
app.use(express.urlencoded({ extended: "true" })); 
app.use(express.json());
app.use(express.json({ type: "application/vnd.api+json" }));
app.use(methodOverride("X-HTTP-Method-Override")); 
app.get("/", (req, res) => {
  res.send("Welcome to my app!!");
});
const PORT = process.env.PORT || 5000;

app.listen(PORT, () => console.log(`App started on port ${PORT}`));
