var tileCollection = [
  
    {
      tileId: "My Profile",
      category: "My Space",
      subcategory: "To-do Items",
      adminId: "",
      itAdminId: "",
      isAdmin_managed: false,
      isDynamic: false,
      forcedEmployee: [""],
      restrictedUsers: [""],
      includedGrades: [""],
      restrictedGrades: [""],
      groupCompanyDetails: [] ,
      url:
        "https://performancemanager4.successfactors.com/sf/liveprofile?company=Mahindra&loginMethod=SSO",
    },
    {
      tileId: "Positive Post-its",
      category: "My Space",
      subcategory: "To-do Items",
      adminId: "",
      itAdminId: "",
      isAdmin_managed: false,
      isDynamic: false,
      forcedEmployee: [""],
      restrictedUsers: [""],
      includedGrades: [""],
      restrictedGrades: [""],
      groupCompanyDetails: [],     
      url:
        "https://performancemanager4.successfactors.com/sf/uxrFeedback/giveFeedback?company=Mahindra&loginMethod=SSO",
    },
    {
      tileId: "Payslip",
      category: "My Space",
      subcategory: "My Payroll",
      adminId: "",
      itAdminId: "",
      isAdmin_managed: false,
      isDynamic: false,
      forcedEmployee: [""],
      restrictedUsers: [""],
      includedGrades: [""],
      restrictedGrades: [""],
      groupCompanyDetails: [],
      url:
        "https://epmobile.mahindra.com/fiori/shells/abap/Fiorilaunchpad.html?sap-ushell-config=headerless#zhr_sf_payslip-display",
    },
    {
      tileId: "Salary Card ",
      category: "My Space",
      subcategory: "My Payroll",
      adminId: "",
      itAdminId: "",
      isAdmin_managed: false,
      isDynamic: false,
      forcedEmployee: [""],
      restrictedUsers: [""],
      includedGrades: [""],
      restrictedGrades: [""],
      groupCompanyDetails: [],
      url:
        "https://epmobile.mahindra.com/fiori/shells/abap/Fiorilaunchpad.html?sap-ushell-config=headerless#SalaryCard-display",
    },
    {
      tileId: "Tax Declaration",
      category: "My Space",
      subcategory: "My Payroll",
      adminId: "",
      itAdminId: "",
      isAdmin_managed: false,
      isDynamic: false,
      forcedEmployee: [""],
      restrictedUsers: [""],
      includedGrades: [""],
      restrictedGrades: [""],
      groupCompanyDetails: [],
      url:
        "https://emss.mahindra.com/sap/bc/webdynpro/sap/zwdhr_c_tax_declaration_2?sap-accessibility=X&sap-accessibilitymode=CLASSIC#",
    },
    {
      tileId: "Flexi Pay",
      category: "My Space",
      subcategory: "My Payroll",
      adminId: "",
      itAdminId: "",
      isAdmin_managed: false,
      isDynamic: false,
      forcedEmployee: [""],
      restrictedUsers: [""],
      includedGrades: [""],
      restrictedGrades: [""],
      groupCompanyDetails: [],
      url: "https://emss.mahindra.com/sap/bc/webdynpro/sap/zwdhr_a_my_ctc#",
    },
    {
      tileId: "80G Donation ",
      category: "My Space",
      subcategory: "My Payroll",
      adminId: "",
      itAdminId: "",
      isAdmin_managed: false,
      isDynamic: false,
      forcedEmployee: [""],
      restrictedUsers: [""],
      includedGrades: [""],
      restrictedGrades: [""],
      groupCompanyDetails: [],
      url:
        "https://epmobile.mahindra.com/fiori/shells/abap/Fiorilaunchpad.html?sap-ushell-config=headerless#Employee80G-display",
    },
    {
      tileId: "Form16",
      category: "My Space",
      subcategory: "My Payroll", 
      adminId: "",
      itAdminId: "",
      isAdmin_managed: false,
      isDynamic: false,
      forcedEmployee: [""],
      restrictedUsers: [""],
      includedGrades: [""],
      restrictedGrades: [""],
      groupCompanyDetails: [],
      url:
        "https://epmobile.mahindra.com/sap/bc/ui5_ui5/ui2/ushell/shells/abap/fiorilaunchpad.html?sap-ushell-config=headerless#zhr_sf_form16-display",
    },
    {
      tileId: "Retirals",
      category: "My Space",
      subcategory: "My Payroll",
      adminId: "",
      itAdminId: "",
      isAdmin_managed: false,
      isDynamic: false,
      forcedEmployee: [""],
      restrictedUsers: [""],
      includedGrades: [""],
      restrictedGrades: [""],
      groupCompanyDetails: [],
      url:
        "https://epmobile.mahindra.com/sap/bc/ui5_ui5/ui2/ushell/shells/abap/fiorilaunchpad.html?sap-ushell-config=headerless#ZEMPLBENSCH2-display",
    },
    {
      tileId: "R&R Portal",
      category: "My Space",
      subcategory: "My Rewards",
      adminId: "",
      itAdminId: "",
      isAdmin_managed: false,
      isDynamic: false,
      forcedEmployee: [""],
      restrictedUsers: [""],
      includedGrades: [""],
      restrictedGrades: [""],
      groupCompanyDetails: [],
      url: "http://www.afsrecognitionportal.com:8081/",
    },
    {
      tileId: "Comp Revision / PP Letters ",
      category: "My Space",
      subcategory: "My Rewards",
      adminId: "",
      itAdminId: "",
      isAdmin_managed: false,
      isDynamic: false,
      forcedEmployee: [""],
      restrictedUsers: [""],
      includedGrades: [""],
      restrictedGrades: [""],
      groupCompanyDetails: [],   
      url:
        "https://epmobile.mahindra.com/sap/bc/ui5_ui5/ui2/ushell/shells/abap/fiorilaunchpad.html?sap-client=100&&sap-ushell-config=headerless&sap-language=EN&sap-sec_session_created=X&_s.crb=ppHymKSiezMC3Rn1aURfYhLLrs8%3d#Compensation_PPLetters-display",
    },
  
    {
      tileId: "M-ESOP(Exercise Option)",
      category: "My Space",
      subcategory: "My Rewards",
      adminId: "",
      itAdminId: "",
      isAdmin_managed: false,
      isDynamic: false,
      forcedEmployee: [""],
      restrictedUsers: [""],
      includedGrades: [""],
      restrictedGrades: [""],
      groupCompanyDetails: [],
      url: "https://www.mesop.in/SSO/Default.aspx",
    },
  
    {
      tileId: "ESOP Letters ",
      category: "My Space",
      subcategory: "My Rewards",
      adminId: "",
      itAdminId: "",
      isAdmin_managed: false,
      isDynamic: false,
      forcedEmployee: [""],
      restrictedUsers: [""],
      includedGrades: [""],
      restrictedGrades: [""],
      groupCompanyDetails: [],
      url:
        "https://epmobile.mahindra.com/fiori/shells/abap/Fiorilaunchpad.html?sap-ushell-config=headerless#ZHR_ESOPLETTERS-display",
    },
  
    {
      tileId: "LTI Letters",
      category: "My Space",
      subcategory: "My Rewards",
      adminId: "",
      itAdminId: "",
      isAdmin_managed: false,
      isDynamic: false,
      forcedEmployee: [""],
      restrictedUsers: [""],
      includedGrades: [""],
      restrictedGrades: [""],
      groupCompanyDetails: [],
      url:
        "https://emss.mahindra.com/sap/bc/webdynpro/sap/zwdhr_a_lti_employee?sap-accessibility=X&sap-accessibilitymode=CLASSIC#",
    },
    {
      tileId: "Onboarding Activities",
      category: "My Tasks",
      subcategory: "To-do Items",
      adminId: "",
      itAdminId: "",
      isAdmin_managed: false,
      isDynamic: true,
      forcedEmployee: [""],
      restrictedUsers: [""],
      includedGrades: [""],
      restrictedGrades: [""],
      groupCompanyDetails: [],
      url: "",
    },
    {
      tileId: "Update your Profile",
      category: "My Tasks",
      subcategory: "To-do Items",
      adminId: "",
      itAdminId: "",
      isAdmin_managed: false,
      isDynamic: true,
      forcedEmployee: [""],
      restrictedUsers: [""],
      includedGrades: [""],
      restrictedGrades: [""],
      groupCompanyDetails: [],
      url: "",
    },
    {
      tileId: "Take Survey",
      category: "My Tasks",
      subcategory: "To-do Items",
      adminId: "",
      itAdminId: "",
      isAdmin_managed: false,
      isDynamic: true,
      forcedEmployee: [""],
      restrictedUsers: [""],
      includedGrades: [""],
      restrictedGrades: [""],
      groupCompanyDetails: [],
      url: "",
    },
    {
      tileId: "Take Courses",
      category: "My Tasks",
      subcategory: "To-do Items",
      adminId: "",
      itAdminId: "",
      isAdmin_managed: false,
      isDynamic: true,
      forcedEmployee: [""],
      restrictedUsers: [""],
      includedGrades: [""],
      restrictedGrades: [""],
      groupCompanyDetails: [],
      url: "",
    },
    {
      tileId: "Approve Requests",
      category: "My Tasks",
      subcategory: "To-do Items",
      adminId: "",
      itAdminId: "",
      isAdmin_managed: false,
      isDynamic: true,
      forcedEmployee: [""],
      restrictedUsers: [""],
      includedGrades: [""],
      restrictedGrades: [""],
      groupCompanyDetails: [],
      url: "",
    },
    {
      tileId: "Review Performance (PMGM Forms)",
      category: "My Tasks",
      subcategory: "To-do Items",
      adminId: "",
      itAdminId: "",
      isAdmin_managed: false,
      isDynamic: true,
      forcedEmployee: [""],
      restrictedUsers: [""],
      includedGrades: [""],
      restrictedGrades: [""],
      groupCompanyDetails: [],
      url: "",
    },
    {
      tileId: "Benefits (Non CTC Claims) Registration",
      category: "My Space",
      subcategory: "My Benefits",
      adminId: "",
      itAdminId: "",
      isAdmin_managed: false,
      isDynamic: false,
      forcedEmployee: [""],
      restrictedUsers: [""],
      includedGrades: [""],
      restrictedGrades: [""],
      groupCompanyDetails: [],
      url:
        "https://epmobile.mahindra.com/sap/bc/ui5_ui5/ui2/ushell/shells/abap/fiorilaunchpad.html?sap-client=100&sap-language=EN&sap-ushell-config=headerless&sap-sec_session_created=X#zhr_my_benefits_semobj-display",
    },
    {
      tileId: "Non CTC Claims",
      category: "My Space",
      subcategory: "My Benefits",
      adminId: "",
      itAdminId: "",
      isAdmin_managed: false,
      isDynamic: false,
      forcedEmployee: [""],
      restrictedUsers: [""],
      includedGrades: [""],
      restrictedGrades: [""],
      groupCompanyDetails: [],
      url:
        "https://epmobile.mahindra.com/sap/bc/ui5_ui5/ui2/ushell/shells/abap/fiorilaunchpad.html?sap-client=100&sap-language=EN&sap-ushell-config=headerless&sap-sec_session_created=X#zhr_my_benefits_semobj-display",
    },
    {
      tileId: "Medical Reimbursement ",
      category: "My Space",
      subcategory: "My Benefits",
      adminId: "",
      itAdminId: "",
      isAdmin_managed: false,
      isDynamic: false,
      forcedEmployee: [""],
      restrictedUsers: [""],
      includedGrades: [""],
      restrictedGrades: [""],
      groupCompanyDetails: [],
      url: "",
    },
    {
      tileId: "LTA Claim",
      category: "My Space",
      subcategory: "My Benefits",
      adminId: "",
      itAdminId: "",
      isAdmin_managed: false,
      isDynamic: false,
      forcedEmployee: [""],
      restrictedUsers: [""],
      includedGrades: [""],
      restrictedGrades: [""],
      groupCompanyDetails: [],
      url: "",
    },
    {
      tileId: "Dependent Medical Insurance",
      category: "My Space",
      subcategory: "My Benefits",
      adminId: "",
      itAdminId: "",
      isAdmin_managed: false,
      isDynamic: false,
      forcedEmployee: [""],
      restrictedUsers: [""],
      includedGrades: [""],
      restrictedGrades: [""],
      groupCompanyDetails: [],
      url:
        "https://emss.mahindra.com/sap/bc/webdynpro/sap/zwdhr_family_medi_insuran?sap-theme=ZSAP_CORBU1",
    },
    {
      tileId: "Employee Car Lease Scheme",
      category: "My Space",
      subcategory: "My Benefits",
      adminId: "",
      itAdminId: "",
      isAdmin_managed: false,
      isDynamic: false,
      forcedEmployee: [""],
      restrictedUsers: [""],
      includedGrades: [""],
      restrictedGrades: [""],
      groupCompanyDetails: [],
      url: "https://www.carandbike.com/leasing",
    },
    {
      tileId: "Correspondance Letters",
      category: "My Space",
      subcategory: "My Letters",
      adminId: "",
      itAdminId: "",
      isAdmin_managed: false,
      isDynamic: false,
      forcedEmployee: [""],
      restrictedUsers: [""],
      includedGrades: [""],
      restrictedGrades: [""],
      groupCompanyDetails: [],
      url:
        "https://emss.mahindra.com/sap/bc/webdynpro/sap/zwdhr_a_corr_letters_ess#",
    },
    {
      tileId: "Other Letters (Confirmation Letters)",
      category: "My Space",
      subcategory: "My Letters",
      adminId: "",
      itAdminId: "",
      isAdmin_managed: false,
      isDynamic: false,
      forcedEmployee: [""],
      restrictedUsers: [""],
      includedGrades: [""],
      restrictedGrades: [""],
      groupCompanyDetails: [],
      url:
        "https://epmobile.mahindra.com/fiori/shells/abap/Fiorilaunchpad.html?sap-ushell-config=headerless#ZHR_CONF_LTR-display",
    },
    {
      tileId: "Travel Request",
      category: "My Space",
      subcategory: "My Letters",
      adminId: "",
      itAdminId: "",
      isAdmin_managed: false,
      isDynamic: false,
      forcedEmployee: [""],
      restrictedUsers: [""],
      includedGrades: [""],
      restrictedGrades: [""],
      groupCompanyDetails: [],
      url:
        "https://epmobile.mahindra.com/sap/bc/ui5_ui5/ui2/ushell/shells/abap/fiorilaunchpad.html?sap-ushell-config=headerless&sap-client=100&sap-language=EN#zdom_trvl_mgmnt-display",
    },
    {
      tileId: "Digital Learning World (DLW)",
      category: "My Space",
      subcategory: "My Letters",
      adminId: "",
      itAdminId: "",
      isAdmin_managed: false,
      isDynamic: false,
      forcedEmployee: [""],
      restrictedUsers: [""],
      includedGrades: [""],
      restrictedGrades: [""],
      groupCompanyDetails: [],
      otherGroupCompanies: [
        {
          companyName: "",
          personnelAreaName: "",
          employeeGroup: [""],
        },
      ],
      url:
        "https:5//mahindra.plateau.com/learning/user/personal/landOnPortalHome.do?OWASP_CSRFTOKEN=JHPM-E4V0-ZTZC-WAA9-5K9D-SOSO-S75X-TBZO&fromSF=Y&fromDeepLink=null&fromDeepLink=true&pageID=&pageID=",
    },
    {
      tileId: "HMM SPARK",
      category: "My Space",
      subcategory: "My Letters",
      adminId: "",
      itAdminId: "",
      isAdmin_managed: false,
      isDynamic: false,
      forcedEmployee: [""],
      restrictedUsers: [""],
      includedGrades: [""],
      restrictedGrades: [""],
      groupCompanyDetails: [],
      url: "https://mahindra.myhbp.org/lde/",
    },
    {
      tileId: "Genie - Raise a Query",
      category: "My Space",
      subcategory: "My Letters",
      adminId: "",
      itAdminId: "",
      isAdmin_managed: false,
      isDynamic: false,
      forcedEmployee: [""],
      restrictedUsers: [""],
      includedGrades: [""],
      restrictedGrades: [""],
      groupCompanyDetails: [],
      url: "https://mapps.mahindra.com/Genie/",
    },
    {
      tileId: "My Time Off",
      category: "My Space",
      subcategory: "My Letters",
      adminId: "",
      itAdminId: "",
      isAdmin_managed: false,
      isDynamic: false,
      forcedEmployee: [""],
      restrictedUsers: [""],
      includedGrades: [""],
      restrictedGrades: [""],
      groupCompanyDetails: [],
      url:
        "https://performancemanager4.successfactors.com/sf/timeoff?company=Mahindra&loginMethod=SSO",
    },
    {
      tileId: "Approval Center",
      category: "My Space",
      subcategory: "My Letters",
      adminId: "",
      itAdminId: "",
      isAdmin_managed: false,
      isDynamic: false,
      forcedEmployee: [""],
      restrictedUsers: [""],
      includedGrades: [""],
      restrictedGrades: [""],
      groupCompanyDetails: [], 
      url:
        "https://epmobile.mahindra.com/sap/bc/ui5_ui5/ui2/ushell/shells/abap/fiorilaunchpad.html?sap-ushell-config=headerless#ZHR_ALL_APRV-display",
    },
    {
      tileId: "GRC",
      category: "My Space",
      subcategory: "My Letters",
      adminId: "",
      itAdminId: "",
      isAdmin_managed: false,
      isDynamic: false,
      forcedEmployee: [""],
      restrictedUsers: [""],
      includedGrades: [""],
      restrictedGrades: [""],
      groupCompanyDetails: [],
      url:
        "https://epmobile.mahindra.com/sap/bc/ui5_ui5/ui2/ushell/shells/abap/fiorilaunchpad.html?sap-ushell-config=headerless&sap-client=100#ZZACCESSREQUEST-CREATE",
    },
    {
      tileId: "Quick Links(PR & ORG.CHART)",
      category: "My Space",
      subcategory: "My Letters",
      adminId: "",
      itAdminId: "",
      isAdmin_managed: false,
      isDynamic: false,
      forcedEmployee: [""],
      restrictedUsers: [""],
      includedGrades: [""],
      restrictedGrades: [""],
      groupCompanyDetails: [],
      url: "",
    },
    {
      tileId: "Manage My team",
      category: "My Team",
      adminId: "",
      itAdminId: "",
      isAdmin_managed: false,
      isDynamic: false,
      forcedEmployee: [""],
      restrictedUsers: [""],
      includedGrades: [""],
      restrictedGrades: [""],
      groupCompanyDetails: [],
      url: "",
    },
    {
      tileId: "Team Insights",
      category: "My Team",
      adminId: "",
      itAdminId: "",
      isAdmin_managed: false,
      isDynamic: false,
      forcedEmployee: [""],
      restrictedUsers: [""],
      includedGrades: [""],
      restrictedGrades: [""],
      groupCompanyDetails: [],
      url: "NA",
    },
    {
      tileId: "My Organization",
      category: "My Team",
      adminId: "",
      itAdminId: "",
      isAdmin_managed: false,
      isDynamic: false,
      forcedEmployee: [""],
      restrictedUsers: [""],
      includedGrades: [""],
      restrictedGrades: [""],
      groupCompanyDetails: [],
      url:
        "https://performancemanager4.successfactors.com/sf/orgchart?company=Mahindra&loginMethod=SSO",
    },
    {
      tileId: "Team Time Off",
      category: "My Team",
      adminId: "",
      itAdminId: "",
      isAdmin_managed: false,
      isDynamic: false,
      forcedEmployee: [""],
      restrictedUsers: [""],
      includedGrades: [""],
      restrictedGrades: [""],
      groupCompanyDetails: [],  
      url:
        "https://performancemanager4.successfactors.com/xi/ui/ect/pages/absence/teamAbsenceCalendar.xhtml?company=Mahindra&loginMethod=SSO",
    },
    {
      tileId: "Talent Management",
      category: "My Team",
      adminId: "",
      itAdminId: "",
      isAdmin_managed: false,
      isDynamic: false,
      forcedEmployee: [""],
      restrictedUsers: [""],
      includedGrades: [""],
      restrictedGrades: [""],
      groupCompanyDetails: [],
      url:
        "https://performancemanager4.successfactors.com/sf/smorgchart?company=Mahindra&loginMethod=SSO",
    },
    {
      tileId: "Annual Appraisal Status F21",
      category: "My Team",
      adminId: "",
      itAdminId: "",
      isAdmin_managed: true,
      isDynamic: true,
      forcedEmployee: [""],
      restrictedUsers: [""],
      includedGrades: [""],
      restrictedGrades: [""],
      groupCompanyDetails: [],
      url: "",
    },
    {
      tileId: "Admin centre",
      category: "My Admin Area",
      adminId: "",
      itAdminId: "",
      isAdmin_managed: true,
      isDynamic: false,
      forcedEmployee: [""],
      restrictedUsers: [""],
      includedGrades: [""],
      restrictedGrades: [""],
      groupCompanyDetails: [],
      url:
        "https://performancemanager4.successfactors.com/sf/admin?bplte_company=Mahindra&_s.crb=wG66t9XspiW4EyVjn0Clg2bAtYMj4zkWdoDB%252fcHjnRc%253d",
    },
    {
      tileId: "Admin Favourites",
      category: "My Admin Area",
      adminId: "",
      itAdminId: "",
      isAdmin_managed: true,
      isDynamic: false,
      forcedEmployee: [""],
      restrictedUsers: [""],
      includedGrades: [""],
      restrictedGrades: [""],
      groupCompanyDetails: [],
      url: "",
    },
    {
      tileId: "Policies & Offerings ",
      category: "My Reports",
      adminId: "",
      itAdminId: "",
      isAdmin_managed: false,
      isDynamic: false,
      forcedEmployee: [""],
      restrictedUsers: [""],
      includedGrades: [""],
      restrictedGrades: [""],
      groupCompanyDetails: [],   
      url:
        "https://epmobile.mahindra.com/sap/bc/ui5_ui5/sap/zhr_policy/index.html?sap-client=100&sap-language=EN&sap-sec_session_created=X",
    },
    {
      tileId: "	Nanhi Kali ",
      category: "My Reports",
      adminId: "",
      itAdminId: "",
      isAdmin_managed: false,
      isDynamic: false,
      forcedEmployee: [""],
      restrictedUsers: [""],
      includedGrades: [""],
      restrictedGrades: [""],
      groupCompanyDetails: [],
      url: "https://emss.mahindra.com/sap/bc/webdynpro/sap/zwda_as_payroll_giving?sap-theme=ZSAP_CORBU1#",
      url1:"https://www.nanhikali.org/",
      
    },
    {
      tileId: "Me Mahindra Experience ",
      category: "My Reports",
      adminId: "",
      itAdminId: "",
      isAdmin_managed: false,
      isDynamic: false,
      forcedEmployee: [""],
      restrictedUsers: [""],
      includedGrades: [""],
      restrictedGrades: [""],
      groupCompanyDetails: [],   
      url:
        "https://app.powerbi.com/view?r=eyJrIjoiODczY2M2MmItY2UyMC00YWIxLTk1NWQtMjVjMjRhMGU4OTRkIiwidCI6IjhjNDg1OGI1LWYwMjAtNDgzYS1iN2VmLTcxZGVkNmU4MTc2NyIsImMiOjEwfQ%3D%3D",
    },
    {
      tileId: "Goal Setting Status F22 (Chart)",
      category: "My Reports",
      adminId: "",
      itAdminId: "",
      isAdmin_managed: true,
      isDynamic: true,
      forcedEmployee: [""],
      restrictedUsers: [""],
      includedGrades: [""],
      restrictedGrades: [""],
      groupCompanyDetails: [],
      url: "",
    },
    {
      tileId: "Home",
      category: "Other Links from Home - Main Menu",
      adminId: "",
      itAdminId: "",
      isAdmin_managed: false,
      isDynamic: false,
      forcedEmployee: [""],
      restrictedUsers: [""],
      includedGrades: [""],
      restrictedGrades: [""],
      groupCompanyDetails: [],
      url:
        "https://performancemanager4.successfactors.com/sf/home?company=Mahindra&loginMethod=SSO",
    },
    {
      tileId: "Goal Sheet",
      category: "Other Links from Home - Main Menu",
      adminId: "",
      itAdminId: "",
      isAdmin_managed: false,
      isDynamic: false,
      forcedEmployee: [""],
      restrictedUsers: [""],
      includedGrades: [""],
      restrictedGrades: [""],
      groupCompanyDetails: [],
      url:
        "https://performancemanager4.successfactors.com/sf/goals?company=Mahindra&loginMethod=SSO",
    },
    {
      tileId: "Performance & Development Work Area",
      category: "Other Links from Home - Main Menu",
      adminId: "",
      itAdminId: "",
      isAdmin_managed: false,
      isDynamic: false,
      forcedEmployee: [""],
      restrictedUsers: [""],
      includedGrades: [""],
      restrictedGrades: [""],
      groupCompanyDetails: [],
      url:
        "https://performancemanager4.successfactors.com/sf/pmreviews?company=Mahindra&loginMethod=SSO",
    },
    {
      tileId: "Continuous Performance",
      category: "Other Links from Home - Main Menu",
      adminId: "",
      itAdminId: "",
      isAdmin_managed: false,
      isDynamic: false,
      forcedEmployee: [""],
      restrictedUsers: [""],
      includedGrades: [""],
      restrictedGrades: [""],
      groupCompanyDetails: [],
      url:
        "https://performancemanager4.successfactors.com/xi/ui/talentuxr/pages/index.xhtml?company=Mahindra&loginMethod=SSO",
    },
    {
      tileId: "	Continuous Feedback",
      category: "Other Links from Home - Main Menu",
      adminId: "",
      itAdminId: "",
      isAdmin_managed: false,
      isDynamic: false,
      forcedEmployee: [""],
      restrictedUsers: [""],
      includedGrades: [""],
      restrictedGrades: [""],
      groupCompanyDetails: [],
      url: "",
    },
    {
      tileId: "Rating Panel Review",
      category: "Other Links from Home - Main Menu",
      adminId: "",
      itAdminId: "",
      isAdmin_managed: true,
      isDynamic: false,
      forcedEmployee: [""],
      restrictedUsers: [""],
      includedGrades: [""],
      restrictedGrades: [""],
      groupCompanyDetails: [],
      url:
        "https://performancemanager4.successfactors.com/xi/ui/calibration/pages/v2/sessionList.xhtml?company=Mahindra&loginMethod=SSO",
    },
    {
      tileId: "Compensation",
      category: "Other Links from Home - Main Menu",
      adminId: "",
      itAdminId: "",
      isAdmin_managed: true,
      isDynamic: false,
      forcedEmployee: [""],
      restrictedUsers: [""],
      includedGrades: [""],
      restrictedGrades: [""],
      groupCompanyDetails: [],
      url:
        "https://performancemanager4.successfactors.com/acme?company=Mahindra&loginMethod=SSO&fbacme_n=my_forms&inbox_fbfl_ftype=Compensation",
    },
    {
      tileId: "Internal Job Portal",
      category: "Other Links from Home - Main Menu",
      adminId: "",
      itAdminId: "",
      isAdmin_managed: false,
      isDynamic: false,
      forcedEmployee: [""],
      restrictedUsers: [""],
      includedGrades: [""],
      restrictedGrades: [""],
      groupCompanyDetails: [],
      url:
        "https://performancemanager4.successfactors.com/sf/careers/jobsearch?company=Mahindra&loginMethod=SSO",
    },
    {
      tileId: "Internal Job Portal(Zing HR)",
      category: "Other Links from Home - Main Menu",
      adminId: "",
      itAdminId: "",
      isAdmin_managed: false,
      isDynamic: false,
      forcedEmployee: [""],
      restrictedUsers: [""],
      includedGrades: [""],
      restrictedGrades: [""],
      groupCompanyDetails: [],
      url: "https://mahindraijp.zinghr.com/IJP",
    },
    {
      tileId: "Talent Management",
      category: "Other Links from Home - Main Menu",
      adminId: "",
      itAdminId: "",
      isAdmin_managed: true,
      isDynamic: false,
      forcedEmployee: [""],
      restrictedUsers: [""],
      includedGrades: [""],
      restrictedGrades: [""],
      groupCompanyDetails: [],
      url: "",
    },
    {
      tileId: "Recruiting (Job Requiistions)",
      category: "Other Links from Home - Main Menu",
      adminId: "",
      itAdminId: "",
      isAdmin_managed: true,
      isDynamic: false,
      forcedEmployee: [""],
      restrictedUsers: [""],
      includedGrades: [""],
      restrictedGrades: [""],
      groupCompanyDetails: [],   
      url:
        "https://performancemanager4.successfactors.com/xi/ui/rcmjobreqsummary/pages/jobReqSummary.xhtml?company=Mahindra&loginMethod=SSO",
    },
  
    {
      tileId: "On-OffBoarding",
      category: "Other Links from Home - Main Menu",
      adminId: "",
      itAdminId: "",
      isAdmin_managed: true,
      isDynamic: false,
      forcedEmployee: [""],
      restrictedUsers: [""],
      includedGrades: [""],
      restrictedGrades: [""],
      groupCompanyDetails: [],   
      url:
        "https://performancemanager4.successfactors.com/xi/ui/onboarding/pages/dashboard.xhtml?company=Mahindra&loginMethod=SSO",
    },
    {
      tileId: "Presentations",
      category: "Other Links from Home - Main Menu",
      adminId: "",
      itAdminId: "",
      isAdmin_managed: true,
      isDynamic: false,
      forcedEmployee: [""],
      restrictedUsers: [""],
      includedGrades: [""],
      restrictedGrades: [""],
      groupCompanyDetails: [],
      url:
        "https://performancemanager4.successfactors.com/xi/ui/talentreview/pages/talentReview.xhtml?company=Mahindra&loginMethod=SSO",
    },
    {
      tileId: "Org chart and Employee Directory",
      category: "Other Links from Home - Main Menu",
      adminId: "",
      itAdminId: "",
      isAdmin_managed: false,
      isDynamic: false,
      forcedEmployee: [""],
      restrictedUsers: [""],
      includedGrades: [""],
      restrictedGrades: [""],
      groupCompanyDetails: [],
      url:
        "https://performancemanager4.successfactors.com/sf/orgchart?company=Mahindra&loginMethod=SSO",
    },
    {
      tileId: "My Profile",
      category: "Other Links from Home - Main Menu",
      adminId: "",
      itAdminId: "",
      isAdmin_managed: false,
      isDynamic: false,
      forcedEmployee: [""],
      restrictedUsers: [""],
      includedGrades: [""],
      restrictedGrades: [""],
      groupCompanyDetails: [],
      url:
        "https://performancemanager4.successfactors.com/xi/ui/peopleprofile/pages/index.xhtml?company=Mahindra&loginMethod=SSO",
    },
    {
      tileId: "Reporting",
      category: "Other Links from Home - Main Menu",
      adminId: "",
      itAdminId: "",
      isAdmin_managed: true,
      isDynamic: false,
      forcedEmployee: [""],
      restrictedUsers: [""],
      includedGrades: [""],
      restrictedGrades: [""],
      groupCompanyDetails: [],
      url:
        "https://performancemanager4.successfactors.com/xi/ui/reportcenter/pages/reportCenter.xhtml?company=Mahindra&loginMethod=SSO		https://performancemanager4.successfactors.com/xi/ui/reportcenter/pages/reportCenter.xhtml?company=Mahindra&loginMethod=SSO",
    },
    {
      tileId: "Admin centre",
      category: "Other Links from Home - Main Menu",
      adminId: "",
      itAdminId: "",
      isAdmin_managed: true,
      isDynamic: false,
      forcedEmployee: [""],
      restrictedUsers: [""],
      includedGrades: [""],
      restrictedGrades: [""],
      groupCompanyDetails: [],
      url:
        "https://performancemanager4.successfactors.com/sf/admin?company=Mahindra&loginMethod=SSO",
    },
    {
      tileId: "360 Feedback",
      category: "Other Links",
      adminId: "",
      itAdminId: "",
      isAdmin_managed: false,
      isDynamic: true,
      forcedEmployee: [""],
      restrictedUsers: [""],
      includedGrades: [""],
      restrictedGrades: [""],
      groupCompanyDetails: [],
      url: 
         "https://samvaad.mahindra.com/360DegreeFeedback/sso",
    },
  ];
  
  