var mongoose = require("mongoose");

// const roleSchema = new mongoose.Schema({
//   roleId: { type: String, required: true },
//   roleName: { type: String, required: true },
// });

const employeeSchema = new mongoose.Schema({
  employeeId: { type: String, required: true },
  firstName: { type: String, required: true },
  lastName: { type: String, required: true },
  emailId: { type: String, required: true },
  dateOfBirth: { type: String },
  dateOfJoining: { type: String },
  dateOfSeparation: { type: String },
  title: { type: String },
  gender: { type: String },
  martial_status: { type: String },
  employee_pa: { type: String },
  employee_pa_name: { type: String },
  employee_psa: { type: String },
  employee_psa_name: { type: String },
  employeeType: { type: String },
  employeeTypecode: { type: String },
  employeeGrade: { type: String },
  employeeGradecode: { type: String },
  is_sf: { type: Boolean },
  is_pf_user: { type: Boolean },
  is_mesop_user: { type: Boolean },
  is_sa_user: { type: Boolean },
  is_bhr: { type: Boolean },
  is_manager: { type: Boolean },
  company: { type: String },
  companyName: { type: String },
  sector: { type: String },
  sectorName: { type: String },
  businessUnit: { type: String },
  businessUnitName: { type: String },
  division: { type: String },
  divisionName: { type: String },
  sdivision: { type: String },
  sdivisionName: { type: String },
  department: { type: String },
  departmentName: { type: String },
  sdepartment: { type: String },
  sdepartmentName: { type: String },
  org_unit: { type: String },
  org_unitName: { type: String },
  reportees_count: { type: String },
  businessFunction: { type: String },
  business_function_name: { type: String },
  domain: { type: String },
  domainName: { type: String },
  position: { type: String },
  designation: { type: String },
  manager_id: { type: String },
  bhr_id: { type: String },
  mobile_no: { type: String },
  // dateOfBirth: { type: Date },
  // dateOfJoining: { type: Date },
  // organisationUnitCode: Number,
  // organisationUnitName: { type: String },
  // bHR: { type: mongoose.Schema.Types.ObjectId, ref: "Employee" },
  // position: { type: String },
  // role: [roleSchema],
  // is_reporter: { type: Boolean, required: true },
  // reportsTo: {
  //   managerId: String,
  //   empobjectId: { type: mongoose.Schema.Types.ObjectId, ref: "Employee" },
  // },
  // domain: {
  //   domainName: { type: String },
  //   domainCode: { type: Number },
  // },
  // company: {
  //   companyCode: { type: Number },
  //   companyName: { type: String },
  // },
  // sector: {
  //   sectorCode: { type: Number },
  //   sectorName: { type: String },
  // },
  // businessUnit: {
  //   businessUnitName: String,
  //   businessUnitcode: Number,
  // },
  // division: {
  //   divisionName: String,
  //   divisionId: Number,
  //   subdivision: String,
  // },
  // department: {
  //   departmentCode: Number,
  //   departmentName: String,
  //   subdepartment: String,
  // },
});

const Employee = mongoose.model("Employee", employeeSchema);

module.exports = Employee;
